### PR TITLE
update yodatools to 0.2.0a0

### PR DESCRIPTION
**Pull request by ocefpaf**
The token expired today!

BTW not having to renew your binstar tokens is one of the advantages of moving this to conda-forge :wink:

### CODE REVIEW

**Comment by ocefpaf** [comment]
No idea why the webhook for AppVeyor did not start. But it is running here https://ci.appveyor.com/project/odm2bot/conda-recipes-odm2

**Comment by emiliom** [comment]
So, should I merge?

> The token expired today!

I assume you've renewed the token already?
 
> BTW not having to renew your binstar tokens is one of the advantages of moving this to conda-forge

Yeah ... Please bug us about this again the last week of November!

**Comment by ocefpaf** [comment]
> I assume you've renewed the token already?

See https://github.com/ODM2/conda-recipes-ODM2/pull/67/commits/4be5c218d0cb93b9cb6e84a4b4e8a1a129bd85b2 and https://github.com/ODM2/conda-recipes-ODM2/pull/67/commits/b6e28e5ba700eb0ac5a962a1e7fbef9ac01d21b8

> Yeah ... Please bug us about this again the last week of November!

Will do. With the ending of the contract moving this to conda-forge is the best course of action to keep this up and running.

**Comment by emiliom** [comment]
>> I assume you've renewed the token already?
>
> See 4be5c21 and b6e28e5

Ah, I see that in the listing of commits. Sorry, I'm multi-multi tasking right now :(

Merging ...

**Comment by emiliom** [comment]
Let us know (via the email thread) when the conda package is ready. Thanks for your fast turnaround!

**Comment by ocefpaf** [comment]
> Merging ...

I was waiting for Travis-CI :grimacing:

**Comment by emiliom** [comment]
> I was waiting for Travis-CI 

Sorry ... I thought you were implicitly saying that it was ready to merge.

**Comment by ocefpaf** [comment]
> Sorry ... I thought you were implicitly saying that it was ready to merge.

Nope. I meant I added the tokens. One of them failed but I fixed it in https://github.com/ODM2/conda-recipes-ODM2/commit/e0046e10611d66324a66a53e2e4504beb1bbc1e2

We should be OK now.

**Pull request merged**
