### PR TITLE
Drop Python 3.4 and add Python 3.6

### PR DESCRIPTION
**Pull request by ocefpaf**
~~Just testing... Not ready yet.~~

### CODE REVIEW

**Comment by ocefpaf** [comment]
@emiliom `twisted` is not available for Python 3.6 and hence `spyne` is also unavailable.
Since only `wofpy` uses `spyne` and `wofpy` itself is Python 2 only I believe this is OK for now.

I am not sure about dropping Python 3.4 though. I recommend removing it from the build matrix, but we need to know if there are any users out there relying on Python 3.4. Note that the packages will still be available, we are only terminating the Python 3.,4 updates with this PR.

**Comment by emiliom** [comment]
> twisted is not available for Python 3.6 and hence spyne is also unavailable. Since only wofpy uses spyne and wofpy itself is Python 2 only I believe this is OK for now.

Ok.

> I am not sure about dropping Python 3.4 though. I recommend removing it from the build matrix, but we need to know if there are any users out there relying on Python 3.4. Note that the packages will still be available, we are only terminating the Python 3.,4 updates with this PR.

I'm not sure about Python 3.4 (or 3.x in general) usage in the group. I *think* most of us are still on 2.7 ... I can ask the team, but answers will take some time to trickle in.

My hunch is that if anyone is using Python 3, they're not fixed on 3.4 specifically. But that's only a guess.

**Comment by ocefpaf** [comment]
> My hunch is that if anyone is using Python 3, they're not fixed on 3.4 specifically. But that's only a guess.

I have the same hunch :smile: 

But with the deadline for Python 2 support [approaching](https://pythonclock.org/) it would be nice to slowly move people away from `Python 2.7`.

**Comment by emiliom** [comment]
> But with the deadline for Python 2 support approaching it would be nice to slowly move people away from Python 2.7.

Agreed. I'm finally taking Python 3 seriously, myself, this year.

**Comment by emiliom** [comment]
Thanks. FYI, I forgot to mention that I did ask the group if anyone was relying on Python 3.4. No one said yes. So we're good with this.

**Pull request merged**
