### PR TITLE
Update wofpy to 2.1.0b0

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://github.com/ODM2/WOFpy/releases/tag/v2.1.0b0

### CODE REVIEW

**Comment by emiliom** [comment]
Let me know when you've merged this PR. Looks like it's almost there.

**Comment by ocefpaf** [comment]
> Let me know when you've merged this PR. Looks like it's almost there.

It is late night here and I don't think Travis-CI will finish in the next 1-2 hours.
If you see the green feel free to merge, if not I will do it early tomorrow.

**Comment by emiliom** [comment]
Right, it's late for you! No worries. Good night. -E

**Comment by ocefpaf** [comment]
:tada:

**Comment by emiliom** [comment]
Woo-hoo, the conda package is there now! Thanks!

**Pull request merged**
